### ISSUE TITLE
TypeError: expected str, bytes or os.PathLike object, not NoneType

### ISSUE THREAD

**Issue by Drjacky** [Shapa7276/Frida-Injector#2]
Method 1:
```bash
...
I: Baksmaling classes37.dex...
I: Copying assets and libs...
I: Copying unknown files...
I: Copying original files...
I: Copying META-INF/services directory
I: Removing 1.apk framework file...
1
Scaning Main Activity
Traceback (most recent call last):
  File "Frida-Injector/Frida-Injector.py", line 198, in <module>
    main()
  File "Frida-Injector/Frida-Injector.py", line 187, in main
    SmaliInjection(smali_path)
  File "Frida-Injector/Frida-Injector.py", line 42, in SmaliInjection
    with open(mainactivity,'r') as smalifile:
TypeError: expected str, bytes or os.PathLike object, not NoneType
➜  Frida-Injector git:(master) ✗
```

**Comment by Drjacky** [comment]
Updated apktool from 2.4.1 to 2.7.1 but didn't help

**Comment by Drjacky** [comment]
And with method 2:

```bash
...
I: Removing 1.apk framework file...
2
Downloading Latest Gadget
Downloading Architecture arm
100% [..........................................................................] 6118052 / 6118052Downloading Architecture arm64
100% [..........................................................................] 6921212 / 6921212Downloading Architecture x86
100% [..........................................................................] 7987220 / 7987220Downloading Architecture x86_64
100% [..........................................................................] 7636352 / 7636352Traceback (most recent call last):
  File "Frida-Injector/Frida-Injector.py", line 198, in <module>
    main()
  File "Frida-Injector/Frida-Injector.py", line 192, in main
    inject_native()
  File "Frida-Injector/Frida-Injector.py", line 165, in inject_native
    allnativelib=os.listdir(outputdirectory+'/lib/'+arch_name)
FileNotFoundError: [Errno 2] No such file or directory: 'lol/lib/arm64-v8a\narmeabi-v7a\nx86\nx86_64'
```

**Comment by tibonvill** [comment]
script is broken and needs some fixes for method 2... same error

python3 Frida-Injector.py -i PATH_TO_APK -m 2
I: Using Apktool 2.9.3 on kaspersky.apk
I: Loading resource table...
I: Decoding file-resources...
I: Loading resource table from file: /home/rndl/.local/share/apktool/framework/1.apk
I: Decoding values */* XMLs...
I: Decoding AndroidManifest.xml with resources...
I: Regular manifest package...
I: Baksmaling classes.dex...
I: Baksmaling classes2.dex...
I: Baksmaling classes3.dex...
I: Baksmaling classes4.dex...
I: Baksmaling classes5.dex...
I: Baksmaling classes6.dex...
I: Copying assets and libs...
I: Copying unknown files...
I: Copying original files...
I: Copying META-INF/services directory
I: Removing 1.apk framework file...
2
Downloading Latest Gadget
Downloading Architecture arm version:  16.2.1
100% [..........................................................................] 6151732 / 6151732Downloading Architecture arm64 version:  16.2.1
100% [..........................................................................] 6958884 / 6958884Downloading Architecture x86 version:  16.2.1
100% [..........................................................................] 8023144 / 8023144Downloading Architecture x86_64 version:  16.2.1
100% [..........................................................................] 7678060 / 7678060Traceback (most recent call last):
  File "/home/rndl/android/research/frida/Frida-Injector/Frida-Injector.py", line 216, in <module>
    main()
  File "/home/rndl/android/research/frida/Frida-Injector/Frida-Injector.py", line 210, in main
    inject_native()
  File "/home/rndl/android/research/frida/Frida-Injector/Frida-Injector.py", line 183, in inject_native
    allnativelib=os.listdir(outputdirectory+'/lib/'+arch_name)
FileNotFoundError: [Errno 2] No such file or directory: 'lol/lib/arm64-v8a\narmeabi-v7a'
